version: '3.8'

networks:
  jira-net:
    driver: bridge

services:
  jira:
    container_name: jira-web
    volumes:
      - /resources/mails:/app/resources/mails
      - /resources/static:/app/resources/static
      - /resources/view:/app/resources/view
      - /src/main/resources:/app/resources

    build:
      context: .
      dockerfile: Dockerfile
#     restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # Database credentials
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jira

      # OAuth credentials
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}

      # Mail properties
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}

    depends_on:
      - db
    networks:
      - jira-net

  db:
    image: postgres:15
    container_name: jira-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: jira
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - jira-net


  nginx:
    image: nginx:latest
    container_name: nginx-server
#     volumes:
#       - ./config/nginx.conf:/etc/nginx/nginx.conf
#       - ./config/default.conf:/etc/nginx/conf.d/default.conf
#       - ./resources:/opt/jirarush/resources
    ports:
      - "80:80"
    depends_on:
      - jira
    networks:
      - jira-net
